In [1]:
from scipy.fft import fft, fftfreq, ifft
import numpy as np

# 3.5

In [2]:
N = 8

In [3]:
x = np.array([9]*N)

In [4]:
X = fft(x)

In [5]:
X

array([72.-0.j,  0.+0.j,  0.-0.j,  0.+0.j,  0.-0.j,  0.-0.j,  0.+0.j,
        0.-0.j])

In [6]:
x = np.array([0]*N)
x[0] = 1
x

array([1, 0, 0, 0, 0, 0, 0, 0])

In [8]:
X = fft(x)
X

array([1.-0.j, 1.+0.j, 1.-0.j, 1.+0.j, 1.-0.j, 1.-0.j, 1.+0.j, 1.-0.j])

In [9]:
x_3 = np.roll(x, 1)
x_3

array([0, 1, 0, 0, 0, 0, 0, 0])

In [10]:
X_3 = fft(x_3)
X_3

array([ 1.        -0.j        ,  0.70710678-0.70710678j,
        0.        -1.j        , -0.70710678-0.70710678j,
       -1.        -0.j        , -0.70710678+0.70710678j,
        0.        +1.j        ,  0.70710678+0.70710678j])

# 3.6

In [17]:
N = 8
n = np.arange(0, 8, 1)
A = 8
x = (A/4) * np.cos ((3*n+1)/4 * np.pi)
np.around(x, 4)

array([ 1.4142, -2.    ,  1.4142,  0.    , -1.4142,  2.    , -1.4142,
       -0.    ])

In [18]:
X = fft(x)
np.around(X, 4)

array([-0.    -0.j    , -0.    -0.j    , -0.    -0.j    ,  5.6569+5.6569j,
        0.    -0.j    ,  5.6569-5.6569j, -0.    +0.j    , -0.    +0.j    ])